import type { Metadata } from "next";
import "./globals.css";
import ProviderWrappers from "@/core/providers/wrapper";
import { ThemeProvider } from "@/core/providers/theme.provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ProviderWrappers>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </ProviderWrappers>
      </body>
    </html>
  );
}
