import type { Metadata } from "next";
import "./globals.css";
import ProviderWrappers from "@/lib/providers/wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <ProviderWrappers>
          {children}
        </ProviderWrappers>
      </body>
    </html>
  );
}
